
server:
  port: 7774
security:
  oauth2:
    resource:
      filter-order: 99
spring:
  application:
    name: crawler-auth

#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        hbm2ddl:
#          auto: update
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
#    username: root
#    password: 1qaz@WSX