
spring:
  datasource:
    url: jdbc:mysql://www.iamcrawler.cn:3306/micro_order?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name:  com.mysql.jdbc.Driver
  redis:
    host: www.iamcrawler.cn
    port: 6379
    password: 123456
    database: 0
  liquibase:
    change-log: classpath:liquibase\master.xml
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 采用比例，默认 0.1 全部采样 1.0
  zipkin:
    base-url: http://localhost:7773/ # 指定了Zipkin服务器的地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7770/eureka/

security:
  oauth2:
    resource:
      id: test
      user-info-uri: http://localhost:7772/auth/user
      prefer-token-info: false

tx-lcn:
  client:
    manager-address: 127.0.0.1:8070