server:
  port: 7770
spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/iamcrawler/micro
          search-paths: config-repo
          username: iamcrawler
          password: lljy1234
        bootstrap: true
  rabbitmq:
    host: www.iamcrawler.cn
    port: 5672
    username: liuliang
    password: liuliang
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"