server:
  port: 7778
spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/iamcrawler/micro
          search-paths: config-repo
          username: iamcrawler
          password: lljy1234
        bootstrap: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7770/eureka/