server:
  port: 7770
spring:
  application:
    name: crawler-config
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/iamcrawler/micro
          search-paths: config-repo
          username: iamcrawler
          password: lljy1234
        bootstrap: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka/