spring:
  datasource:
    url: jdbc:mysql://www.iamcrawler.cn:3306/micro?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name:  com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0

security:
  oauth2:
    resource:
      id: mall-resource-test
      user-info-uri: http://localhost:5555/auth/user
      prefer-token-info: false

crawler:
  test: liuliang-123